parameters:
  masterOnly: 'false'
  type: 'Docs'
  targetBranch: ''
  ghRef: ''
  dependsOn: ''
  versionSpec: '10.x'

jobs:
- job: ${{ parameters.type }}
  dependsOn: ${{ parameters.dependsOn }}
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: ${{ parameters.versionSpec }}
      displayName: 'Install Node.js'
    - script: yarn
    - bash: |
        set -e
        
        if [[ ("$MASTER_ONLY" = "true" && "$BRANCH" != "master") || "$BUILD_REASON" != "IndividualCI" ]]; then
          echo -e "Not building for a non branch push - building without deploying."
          yarn run docs
          exit 0
        fi

        echo -e "Building for a branch push - building and deploying."

        REPO=$(git config remote.origin.url)
        SHA=$(git rev-parse --verify HEAD)

        git clone $REPO dist -b $TARGET_BRANCH

        yarn run docs

        rsync -vau docs/ dist/

        cd dist
        git add --all .
        git config user.name "Azure Pipelines"
        git config user.email "${COMMIT_EMAIL}"
        git commit -m "${TYPE} build: ${SHA}" || true
        git push "https://${GH_TOKEN}@${GH_REF}" $TARGET_BRANCH
      env:
        BRANCH: $(Build.SourceBranchName)
        BUILD_REASON: $(Build.Reason)
        MASTER_ONLY: ${{ parameters.masterOnly }}
        TYPE: ${{ parameters.type }}
        COMMIT_EMAIL: $(commitEmail)
        GH_TOKEN: $(ghToken)
        GH_REF: ${{ parameters.ghRef }}
        TARGET_BRANCH: ${{ parameters.targetBranch }}