parameters:
  versionSpec: '10.x'

jobs:
- job: "Lint"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: ${{ parameters.versionSpec }}
      displayName: 'Install Node.js'
    - script: yarn
      displayName: 'Install Dependencies'
    - script: 'yarn test:lint'
      displayName: 'Test Lint'